import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Loaiding from "@/components/Loading/page";
import Script from "next/script";

import BodyLayout from "../components/BodyLayout";

import { AuthProvider } from "@/contextapi/provider";
import ReactQueryProvider from "@/contextapi/ReactQueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-[#333333] dark:text-[#F1F5F9] transition-colors lg:max-w-300 lg:mx-auto `}
      >

        <ReactQueryProvider>
          <Loaiding />
          <AuthProvider>
            <BodyLayout>{children}</BodyLayout>
          </AuthProvider>
        </ReactQueryProvider>

        <Loaiding />
        <AuthProvider>
          <BodyLayout>
            <Script
              src={`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_API_KEY}&autoload=false&libraries=services`}
              strategy="beforeInteractive"
            />
            {children}
          </BodyLayout>
        </AuthProvider>

      </body>
    </html>
  );
}
